It calculates the minimum and maximum values for each feature across all samples. Then, it computes the range of each feature. Finally, it normalizes each feature by subtracting the minimum value, dividing by the range, and subtracting from 1 to ensure the values are between 0 and 1. The normalized feature matrix is returned

In [1]:

def normalize(X):

    #function to normalize feature matrix, X

    mins = np.min(X, axis = 0)
    maxs = np.max(X, axis = 0)
    rng = maxs - mins
    norm_X = 1 - ((maxs - X)/rng)
    return norm_X

This code block reads a CSV file named 'dataset1 (2).csv' into a pandas DataFrame, converts it to a NumPy array, and then normalizes the feature matrix using the previously defined normalize function. It adds a column of ones to the feature matrix for the intercept term.

Next, it splits the dataset into training and testing sets using the train_test_split function from sklearn.model_selection. Then, it creates a logistic regression model object and trains it on the training data using the fit method.


In [7]:

from sklearn import datasets, linear_model, metrics
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('/content/dataset1 (2).csv')
dataset=np.array(dataset)
X = normalize(dataset[:, :-1])


# stacking columns wth all ones in feature matrix
X = np.hstack((np.matrix(np.ones(X.shape[0])).T, X))
print('\n')
print(X)

# response vector
y = dataset[:, -1]
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                    random_state=1)

# create logistic regression object
reg = linear_model.LogisticRegression()

# train the model using the training sets
reg.fit(X_train, y_train)

# making predictions on the testing set
y_pred = reg.predict(X_test)

# comparing actual response values (y_test) with predicted response values (y_pred)
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)


FileNotFoundError: [Errno 2] No such file or directory: '/content/dataset1 (2).csv'

In [4]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


This code segment utilizes scikit-learn to perform logistic regression classification. It first splits the dataset into training and testing sets using the train_test_split function. Then, it creates a logistic regression model using the LogisticRegression class and fits it to the training data.



In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


This code segment utilizes scikit-learn to perform logistic regression classification. It first splits the dataset into training and testing sets using the train_test_split function. Then, it creates a logistic regression model using the LogisticRegression class and fits it to the training data.

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))



NameError: name 'X' is not defined

This code loads the digit dataset from scikit-learn, specifically the digits dataset containing images of handwritten digits. It then splits the dataset into features (X) and target labels (y).

After splitting, it further divides the data into training and testing sets using the train_test_split function from scikit-learn. Subsequently, it creates a logistic regression model using the LogisticRegression class and trains it on the training data.

In [9]:
from sklearn import datasets, linear_model, metrics

# load the digit dataset
digits = datasets.load_digits()

# defining feature matrix(X) and response vector(y)
X = digits.data
y = digits.target

# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                    random_state=1)

# create logistic regression object
reg = linear_model.LogisticRegression()

# train the model using the training sets
reg.fit(X_train, y_train)

# making predictions on the testing set
y_pred = reg.predict(X_test)

# comparing actual response values (y_test) with predicted response values (y_pred)
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)


Logistic Regression model accuracy(in %): 96.52294853963839


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


This code block utilizes scikit-learn to perform logistic regression classification on a dataset split into training and testing sets. It uses the train_test_split function to split the data, then creates a logistic regression model using the LogisticRegression class and fits it to the training data.

After training, the model predicts the target labels for the testing set using the predict method. It then prints a classification report, confusion matrix, and accuracy score to evaluate the performance of the model on the testing data.

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        63
           1       0.95      0.95      0.95        59
           2       0.98      1.00      0.99        55
           3       0.97      0.96      0.96        68
           4       0.97      0.98      0.98        66
           5       0.96      0.90      0.93        52
           6       1.00      1.00      1.00        54
           7       0.98      0.95      0.97        62
           8       0.89      0.98      0.93        51
           9       0.95      0.94      0.94        64

    accuracy                           0.97       594
   macro avg       0.97      0.97      0.97       594
weighted avg       0.97      0.97      0.97       594

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  1  0  0  0  2  0]
 [ 0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0 65  0  0  0  1  2  0]
 [ 0  1  0  0 65  0  0  0  0  0]
 [ 0  1  1  1  0 47  0  0  0  2]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
